spring:
  datasource:
    dsql:
      clusterId: cluster-identifier
      region: us-east-1
      username: admin
    driver-class-name: software.amazon.jdbc.Driver
    hikari:
      data-source-properties:
        wrapperPlugins: iamDsql
        wrapperDialect: pg
      max-lifetime: 840000
      minimum-idle: 20
      maximum-pool-size: 20
      idle-timeout: 900000
      read-only: true
